language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository -y ppa:ximion/packagekit
    - sudo apt-get update

install:
    - sudo apt-get -y install appstream coreutils autoconf build-essential avahi-daemon avahi-utils libavahi-client-dev libgnutls28-dev libjpeg-dev libnss-mdns libpng-dev zlib1g-dev

script:
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - cd doc ; make ; cd -       # HTML files are not built+installed by default
  - make BUILDROOT=$(readlink -f appdir) install
  - mkdir -p ./appdir/usr/share/doc/html/ipptool ; cp doc/*.html ./appdir/usr/share/doc/html/ipptool/
  - find . -type f -name "*.txt" -exec cp {} ./appdir/ \;
  - find . -type f -name "*.md"  -exec cp {} ./appdir/ \;
  - find . -type f -name README  -exec cp {} ./appdir/ \;
  - find appdir/
  - #rm -rf appdir/usr/include/cups/ # Do not bundle developer stuff
  - sudo mv  ./appdir/usr/sbin/* ./appdir/usr/bin/ ; rm -rf ./appdir/usr/sbin/ # AppRun does not put usr/sbin/ on $PATH
  - mkdir -p ./appdir/usr/share/applications/ ; cp ./appimage/ippsample.desktop ./appdir/usr/share/applications/
  - mkdir -p ./appdir/usr/share/icons/hicolor/512x512/apps/ ; cp ./appimage/printer.png ./appdir/usr/share/icons/hicolor/512x512/apps/
  - mkdir -p ./appdir/usr/share/metainfo ; cp ./appimage/ippsample.appdata.xml ./appdir/usr/share/metainfo/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - ./linuxdeployqt*.AppImage --appimage-version
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -verbose=2
  - # In addition to the main executable, we have additional ones to process
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/ippfind -bundle-non-qt-libs -verbose=2
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/ippproxy -bundle-non-qt-libs -verbose=2
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/ipptool -bundle-non-qt-libs -verbose=2
  - #./linuxdeployqt*.AppImage ./appdir/usr/bin/ipptransform -bundle-non-qt-libs -verbose=2
  - #./linuxdeployqt*.AppImage ./appdir/usr/bin/ipptransform3d -bundle-non-qt-libs -verbose=2
  - # Bundle examples/ and test/
  - mkdir -p ./appdir/usr/share/cups/ipptool/ ; cp -r examples/* test/* ./appdir/usr/share/cups/ipptool/ ; cp -r examples2/* test/* ./appdir/usr/share/cups/ipptool/
  - # Generate AppImage
  - ./linuxdeployqt*.AppImage --appimage-extract
  - rm ./appdir/AppRun ; cp appimage/AppRun appdir/ ; chmod a+x ./appdir/AppRun           # Replace symlink with custom AppRun script
  - PATH=./squashfs-root/usr/bin:$PATH ./squashfs-root/usr/bin/appimagetool -v -u 'gh-releases-zsync|KurtPfeifle|ippsample|continuous|ippsample-*x86_64.AppImage.zsync' -n ./appdir/

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - find . -name "ipp*.AppImage"
  - mv ./ippserver*.AppImage       ./ippsample-xperimental-x86_64.AppImage       || echo "No ippserver*.AppImage"
  - mv ./ippserver*.AppImage.zsync ./ippsample-xperimental-x86_64.AppImage.zsync || echo "No ippserver*.AppImage"
  - mv ./ippsample*.AppImage       ./ippsample-xperimental-x86_64.AppImage       || echo "No ippsample*.AppImage"
  - mv ./ippsample*.AppImage.zsync ./ippsample-xperimental-x86_64.AppImage.zsync || echo "No ippsample*.AppImage"
  - cp ./ippsample-xperimental{,-$(git rev-parse --short HEAD)}-x86_64.AppImage
  - cp ./ippsample-xperimental{,-$(git rev-parse --short HEAD)}-x86_64.AppImage.zsync
  - curl --upload-file ./ippsample-xperimental-x86_64.AppImage                               https://transfer.sh/ippsample-xperimental-x86_64.AppImage
  - curl --upload-file ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage https://transfer.sh/ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - ls -lh ./*.AppImage
  - sha512sum ./ippsample-xperimental-x86_64.AppImage > ./ippsample-xperimental-x86_64.AppImage.sha512
  - md5sum    ./ippsample-xperimental-x86_64.AppImage > ./ippsample-xperimental-x86_64.AppImage.md5
  - find . -name "*.AppImage*"
  - bash ./upload.sh ./ippsample-xperimental-x86_64.AppImage
  - bash ./upload.sh ./ippsample-xperimental-x86_64.AppImage.sha512
  - bash ./upload.sh ./ippsample-xperimental-x86_64.AppImage.zsync
  - cp ./ippsample-xperimental-x86_64.AppImage ./ippsample-x86_64.AppImage
  - mv ./ippsample-xperimental-x86_64.AppImage ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage
  - sha512sum ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage > ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage.sha512
  - md5sum    ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage > ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage.md5
  - bash ./upload.sh ./ippsample-x86_64.AppImage
  - bash ./upload.sh ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage
  - bash ./upload.sh ./ippsample-xperimental-$(git rev-parse --short HEAD)-x86_64.AppImage.sha512
  - bash ./upload.sh ./ippsample-xperimental-*$(git rev-parse --short HEAD)-x86_64.AppImage.zsync
  - find . -name "*.AppImage*"

branches:
  only:
    - master

